# Generated by Django 5.0 on 2026-03-08 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.IntegerField(default=0)),
                ('classes_attended', models.IntegerField(default=0)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.enrollment')),
            ],
        ),
    ]
